/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestingImport } from './routes/testing'
import { Route as ToolsQrReaderIndexImport } from './routes/tools/qr-reader/index'
import { Route as ToolsImageSplitIndexImport } from './routes/tools/image-split/index'
import { Route as ToolsImageCropIndexImport } from './routes/tools/image-crop/index'
import { Route as ToolsImageConcatIndexImport } from './routes/tools/image-concat/index'
import { Route as ToolsGifPlayerIndexImport } from './routes/tools/gif-player/index'
import { Route as ToolsBackgroundRemoveIndexImport } from './routes/tools/background-remove/index'
import { Route as SysTaskManagerIndexImport } from './routes/sys/task-manager/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestingRoute = TestingImport.update({
  path: '/testing',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ToolsQrReaderIndexRoute = ToolsQrReaderIndexImport.update({
  path: '/tools/qr-reader/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/qr-reader/index.lazy').then((d) => d.Route),
)

const ToolsImageSplitIndexRoute = ToolsImageSplitIndexImport.update({
  path: '/tools/image-split/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/image-split/index.lazy').then((d) => d.Route),
)

const ToolsImageCropIndexRoute = ToolsImageCropIndexImport.update({
  path: '/tools/image-crop/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/image-crop/index.lazy').then((d) => d.Route),
)

const ToolsImageConcatIndexRoute = ToolsImageConcatIndexImport.update({
  path: '/tools/image-concat/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/image-concat/index.lazy').then((d) => d.Route),
)

const ToolsGifPlayerIndexRoute = ToolsGifPlayerIndexImport.update({
  path: '/tools/gif-player/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/gif-player/index.lazy').then((d) => d.Route),
)

const ToolsBackgroundRemoveIndexRoute = ToolsBackgroundRemoveIndexImport.update(
  {
    path: '/tools/background-remove/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/tools/background-remove/index.lazy').then((d) => d.Route),
)

const SysTaskManagerIndexRoute = SysTaskManagerIndexImport.update({
  path: '/sys/task-manager/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sys/task-manager/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingImport
      parentRoute: typeof rootRoute
    }
    '/sys/task-manager/': {
      id: '/sys/task-manager/'
      path: '/sys/task-manager'
      fullPath: '/sys/task-manager'
      preLoaderRoute: typeof SysTaskManagerIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/background-remove/': {
      id: '/tools/background-remove/'
      path: '/tools/background-remove'
      fullPath: '/tools/background-remove'
      preLoaderRoute: typeof ToolsBackgroundRemoveIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/gif-player/': {
      id: '/tools/gif-player/'
      path: '/tools/gif-player'
      fullPath: '/tools/gif-player'
      preLoaderRoute: typeof ToolsGifPlayerIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/image-concat/': {
      id: '/tools/image-concat/'
      path: '/tools/image-concat'
      fullPath: '/tools/image-concat'
      preLoaderRoute: typeof ToolsImageConcatIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/image-crop/': {
      id: '/tools/image-crop/'
      path: '/tools/image-crop'
      fullPath: '/tools/image-crop'
      preLoaderRoute: typeof ToolsImageCropIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/image-split/': {
      id: '/tools/image-split/'
      path: '/tools/image-split'
      fullPath: '/tools/image-split'
      preLoaderRoute: typeof ToolsImageSplitIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/qr-reader/': {
      id: '/tools/qr-reader/'
      path: '/tools/qr-reader'
      fullPath: '/tools/qr-reader'
      preLoaderRoute: typeof ToolsQrReaderIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/testing': typeof TestingRoute
  '/sys/task-manager': typeof SysTaskManagerIndexRoute
  '/tools/background-remove': typeof ToolsBackgroundRemoveIndexRoute
  '/tools/gif-player': typeof ToolsGifPlayerIndexRoute
  '/tools/image-concat': typeof ToolsImageConcatIndexRoute
  '/tools/image-crop': typeof ToolsImageCropIndexRoute
  '/tools/image-split': typeof ToolsImageSplitIndexRoute
  '/tools/qr-reader': typeof ToolsQrReaderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/testing': typeof TestingRoute
  '/sys/task-manager': typeof SysTaskManagerIndexRoute
  '/tools/background-remove': typeof ToolsBackgroundRemoveIndexRoute
  '/tools/gif-player': typeof ToolsGifPlayerIndexRoute
  '/tools/image-concat': typeof ToolsImageConcatIndexRoute
  '/tools/image-crop': typeof ToolsImageCropIndexRoute
  '/tools/image-split': typeof ToolsImageSplitIndexRoute
  '/tools/qr-reader': typeof ToolsQrReaderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/testing': typeof TestingRoute
  '/sys/task-manager/': typeof SysTaskManagerIndexRoute
  '/tools/background-remove/': typeof ToolsBackgroundRemoveIndexRoute
  '/tools/gif-player/': typeof ToolsGifPlayerIndexRoute
  '/tools/image-concat/': typeof ToolsImageConcatIndexRoute
  '/tools/image-crop/': typeof ToolsImageCropIndexRoute
  '/tools/image-split/': typeof ToolsImageSplitIndexRoute
  '/tools/qr-reader/': typeof ToolsQrReaderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/testing'
    | '/sys/task-manager'
    | '/tools/background-remove'
    | '/tools/gif-player'
    | '/tools/image-concat'
    | '/tools/image-crop'
    | '/tools/image-split'
    | '/tools/qr-reader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/testing'
    | '/sys/task-manager'
    | '/tools/background-remove'
    | '/tools/gif-player'
    | '/tools/image-concat'
    | '/tools/image-crop'
    | '/tools/image-split'
    | '/tools/qr-reader'
  id:
    | '__root__'
    | '/'
    | '/testing'
    | '/sys/task-manager/'
    | '/tools/background-remove/'
    | '/tools/gif-player/'
    | '/tools/image-concat/'
    | '/tools/image-crop/'
    | '/tools/image-split/'
    | '/tools/qr-reader/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TestingRoute: typeof TestingRoute
  SysTaskManagerIndexRoute: typeof SysTaskManagerIndexRoute
  ToolsBackgroundRemoveIndexRoute: typeof ToolsBackgroundRemoveIndexRoute
  ToolsGifPlayerIndexRoute: typeof ToolsGifPlayerIndexRoute
  ToolsImageConcatIndexRoute: typeof ToolsImageConcatIndexRoute
  ToolsImageCropIndexRoute: typeof ToolsImageCropIndexRoute
  ToolsImageSplitIndexRoute: typeof ToolsImageSplitIndexRoute
  ToolsQrReaderIndexRoute: typeof ToolsQrReaderIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TestingRoute: TestingRoute,
  SysTaskManagerIndexRoute: SysTaskManagerIndexRoute,
  ToolsBackgroundRemoveIndexRoute: ToolsBackgroundRemoveIndexRoute,
  ToolsGifPlayerIndexRoute: ToolsGifPlayerIndexRoute,
  ToolsImageConcatIndexRoute: ToolsImageConcatIndexRoute,
  ToolsImageCropIndexRoute: ToolsImageCropIndexRoute,
  ToolsImageSplitIndexRoute: ToolsImageSplitIndexRoute,
  ToolsQrReaderIndexRoute: ToolsQrReaderIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/testing",
        "/sys/task-manager/",
        "/tools/background-remove/",
        "/tools/gif-player/",
        "/tools/image-concat/",
        "/tools/image-crop/",
        "/tools/image-split/",
        "/tools/qr-reader/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/testing": {
      "filePath": "testing.tsx"
    },
    "/sys/task-manager/": {
      "filePath": "sys/task-manager/index.tsx"
    },
    "/tools/background-remove/": {
      "filePath": "tools/background-remove/index.tsx"
    },
    "/tools/gif-player/": {
      "filePath": "tools/gif-player/index.tsx"
    },
    "/tools/image-concat/": {
      "filePath": "tools/image-concat/index.tsx"
    },
    "/tools/image-crop/": {
      "filePath": "tools/image-crop/index.tsx"
    },
    "/tools/image-split/": {
      "filePath": "tools/image-split/index.tsx"
    },
    "/tools/qr-reader/": {
      "filePath": "tools/qr-reader/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
